"""add surveys schema

Revision ID: c734a193ce14
Revises: 940ebc48c1de
Create Date: 2026-01-25 13:50:41.721631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c734a193ce14'
down_revision: Union[str, Sequence[str], None] = '940ebc48c1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ARCHIVED', name='survey_status'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='survey_version_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'version_number', name='uq_survey_versions_survey_id_version_number')
    )
    op.create_table('survey_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('SCALE', 'SINGLE_CHOICE', 'MULTI_CHOICE', 'TEXT', name='survey_question_type'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_survey_questions_display_order_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'question_key', name='uq_survey_questions_version_id_question_key')
    )
    op.create_table('survey_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['survey_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'user_id', name='uq_survey_submissions_version_id_user_id')
    )
    op.create_table('survey_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['survey_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_survey_answers_submission_id_question_id')
    )
    op.drop_column('audit_logs', 'action')
    op.drop_column('audit_logs', 'endpoint')
    op.drop_column('audit_logs', 'actor_role')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'actor_user_id')
    op.drop_column('teams', 'name')
    op.drop_column('teams', 'department')
    op.drop_column('teams', 'created_at')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(op.f('users_team_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'email')
    op.drop_column('users', 'role')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'team_id')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_team_id_fkey'), 'users', 'teams', ['team_id'], ['id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('teams', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('department', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('teams', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('actor_role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('endpoint', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_table('survey_answers')
    op.drop_table('survey_submissions')
    op.drop_table('survey_questions')
    op.drop_table('survey_versions')
    op.drop_table('surveys')
    # ### end Alembic commands ###
